type          ::Mutex
new           ::Mutex*::new                   Mutex
acquire       ::Mutex*::lock
guard         ::MutexGuard

type          ::RwLock
new           ::RwLock*::new                  RwLock
acquire_read  ::RwLock*::read
acquire       ::RwLock*::write
guard_read    ::RwLockReadGuard
guard         ::RwLockWriteGuard
guard_read    ::MappedRwLockReadGuard
guard         ::MappedRwLockWriteGuard

wait          ::RawMutex*::block
wait          ::RawMutex*::block_or_timeout
notify_one    ::RawMutex*::wake_one
notify_all    ::RawMutex*::wake_all

annotate      ::WaitStateInner*::wake          define_lock WAITER = self.condvar
annotate      ::WaitStateInner*::wake          foreign wake, on = self.condvar
annotate      ::ThreadHandle*::interrupt       define_lock WAITER = self.waker.0.condvar
annotate      ::ThreadHandle*::interrupt       foreign wake, on = self.waker.0.condvar
annotate      ::WaitContext*::commit_wait      define_lock WAITER = self.condvar
annotate      ::WaitContext*::commit_wait      foreign wait, on = self.condvar, blocks

annotate      ::FutexManager*::wait            mhp "futex"
annotate      ::FutexManager*::wake            mhp "futex"

annotate      ::LoanList*::remove_node         foreign wait, on = node.data.state, blocks
annotate      ::LoanedEntry*::drop             foreign wake, on = self.entry.data.state

annotate      litebox_platform_linux_userland*::register_cow_region mhp "platform_userland"
annotate      litebox_platform_linux_userland*::wait_on_tun mhp "platform_userland"
annotate      litebox_platform_linux_userland*::send_ip_packet mhp "platform_userland"
annotate      litebox_platform_linux_userland*::receive_ip_packet mhp "platform_userland"
annotate      litebox_platform_linux_userland*::try_allocate_cow_pages mhp "platform_userland"
annotate      litebox_runner_lvbs*::vsm_dispatch mhp_group "vsm"
annotate      litebox_runner_lvbs*::handle_open_session mhp "ta_lvbs"
annotate      litebox_runner_lvbs*::open_session_single_instance mhp "ta_lvbs"
annotate      litebox_runner_lvbs*::open_session_new_instance mhp "ta_lvbs"
annotate      litebox_runner_lvbs*::finalize_dead_session mhp "ta_lvbs"
annotate      litebox_runner_lvbs*::handle_invoke_command mhp "ta_lvbs"
annotate      litebox_runner_lvbs*::handle_close_session mhp "ta_lvbs"
annotate      litebox_service_heki::handlers*::lock_regs mhp "heki"
annotate      litebox_service_heki::handlers*::protect_memory mhp "heki"
annotate      litebox_service_heki::handlers*::load_kdata mhp "heki"
annotate      litebox_service_heki::handlers*::validate_guest_module mhp "heki"
annotate      litebox_service_heki::handlers*::free_guest_module_init mhp "heki"
annotate      litebox_service_heki::handlers*::unload_guest_module mhp "heki"
annotate      litebox_service_heki::handlers*::copy_secondary_key mhp "heki"
annotate      litebox_service_heki::handlers*::kexec_validate mhp "heki"
annotate      litebox_service_heki::handlers*::patch_text mhp "heki"
annotate      litebox_service_heki::handlers*::allocate_ringbuffer_memory mhp "heki"
annotate      litebox_shim_linux::syscalls::file*::sys_umask mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_open mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_openat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_ftruncate mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_mknodat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_unlinkat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_read mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_write mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_pread64 mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_pwrite64 mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_sendfile mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_lseek mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_mkdirat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_close mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_preadv mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_pwritev mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_readv mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_writev mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_faccessat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_readlink mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_readlinkat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_stat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_lstat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_fstat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_newfstatat mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_statx mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_fcntl mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_getcwd mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_chdir mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_pipe2 mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_eventfd2 mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_ioctl mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_epoll_create mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_epoll_ctl mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_epoll_pwait mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_ppoll mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_pselect mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_dup mhp "file"
annotate      litebox_shim_linux::syscalls::file*::sys_getdirent64 mhp "file"
annotate      litebox_shim_linux::syscalls::misc*::sys_getrandom mhp "misc"
annotate      litebox_shim_linux::syscalls::misc*::sys_uname mhp "misc"
annotate      litebox_shim_linux::syscalls::misc*::sys_sysinfo mhp "misc"
annotate      litebox_shim_linux::syscalls::misc*::sys_capget mhp "misc"
annotate      litebox_shim_linux::syscalls::mm*::sys_mmap mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_munmap mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_munmap_raw mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_mprotect mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_mprotect_raw mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_mremap mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_brk mhp "mm"
annotate      litebox_shim_linux::syscalls::mm*::sys_madvise mhp "mm"
annotate      litebox_shim_linux::syscalls::net*::sys_socket mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_socketpair mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_accept mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_connect mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_bind mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_listen mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_sendto mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_sendmsg mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_sendmmsg mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_recvfrom mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_recvmsg mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_recvmmsg mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_setsockopt mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_getsockopt mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_getsockname mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_getpeername mhp "net"
annotate      litebox_shim_linux::syscalls::net*::sys_shutdown mhp "net"
annotate      litebox_shim_linux::syscalls::process*::sys_prctl mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_arch_prctl mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_exit mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_exit_group mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_clone mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_clone3 mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_set_tid_address mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_gettid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_prlimit mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getrlimit mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_setrlimit mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_set_robust_list mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_get_robust_list mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_clock_gettime mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_clock_getres mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_clock_nanosleep mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_gettimeofday mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_time mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_alarm mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_setitimer mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getitimer mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_pause mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getpid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getppid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getuid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_geteuid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getgid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_getegid mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_sched_getaffinity mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_futex mhp "process"
annotate      litebox_shim_linux::syscalls::process*::sys_execve mhp "process"
annotate      litebox_shim_linux::syscalls::signal*::sys_rt_sigprocmask mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_sigaltstack mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_rt_sigreturn mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_rt_sigaction mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_kill mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_tkill mhp "signal"
annotate      litebox_shim_linux::syscalls::signal*::sys_tgkill mhp "signal"
annotate      litebox_shim_optee::idk*::generate_identity_signing_key mhp "vsm"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_state_alloc mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_state_free mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cipher_init mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cipher_update mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cipher_final mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_get_info mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_alloc mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_close mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_reset mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_populate mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::cryp*::sys_cryp_obj_copy mhp "ta_crypto"
annotate      litebox_shim_optee::syscalls::ldelf*::sys_map_zi mhp "ta_ldelf"
annotate      litebox_shim_optee::syscalls::ldelf*::sys_open_bin mhp "ta_ldelf"
annotate      litebox_shim_optee::syscalls::ldelf*::sys_close_bin mhp "ta_ldelf"
annotate      litebox_shim_optee::syscalls::ldelf*::sys_map_bin mhp "ta_ldelf"
annotate      litebox_shim_optee::syscalls::ldelf*::sys_cp_from_bin mhp "ta_ldelf"
annotate      litebox_shim_optee::syscalls::pta*::try_set_busy mhp "ta_session"
annotate      litebox_shim_optee::syscalls::pta*::open_pta_session mhp "ta_session"
annotate      litebox_shim_optee::syscalls::pta*::close_pta_session mhp "ta_session"